import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-screen w-screen bg-gradient-to-b from-blue-100 to-red-100">
          <nav className="h-24">
            <Navbar />
          </nav>
          <section className="h-[calc(100vh - 6rem)]">{children}</section>
        </main>
      </body>
    </html>
  );
}
